LeaveManagementSystem.Web/Controllers/LeaveAllocationController.cs
using LeaveManagementSystem.Application.Models;
using LeaveManagementSystem.Application.Models.LeaveAllocation;
using LeaveManagementSystem.Web.Services.LeaveService;
using Microsoft.AspNetCore.Mvc;

namespace LeaveManagementSystem.Web.Controllers
{
    [Authorize]
    public class LeaveAllocationController : Controller
    {
        private readonly ILeaveAllocationService _leaveAllocationService;
        private readonly ILeaveTypeService _leaveTypeService;

        public LeaveAllocationController(ILeaveAllocationService leaveAllocationService ,ILeaveTypeService leaveTypeService)
        {
            _leaveAllocationService = leaveAllocationService;
            _leaveTypeService = leaveTypeService;
        }
        [Authorize(Roles = UserRoles.administrator)]
        public async Task<IActionResult> Index()
        {
            var Employees = await _leaveAllocationService.GetEmployees();

            return View(Employees);
        }


        [Authorize(Roles = UserRoles.administrator)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> AllocateLeave(string? Id)
        {
            await _leaveAllocationService.AllocateLeave(Id);

            return RedirectToAction(nameof(Details),new { UserId= Id }); //passed parameter 
        }
        
        [Authorize(Roles= UserRoles.administrator)]
        public async Task<IActionResult> EditAllocation(int ? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var allocation = await _leaveAllocationService.GetAllocationForEmployee(Id.Value);
            if(allocation is null)
            {
                return NotFound();
            }


            return View(allocation);
        }

        [Authorize(Roles = UserRoles.administrator)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAllocation(LeaveAllocationEditVM leaveAllocationEdit)
        {
            if ( await _leaveTypeService.DaysExceedMaximum(leaveAllocationEdit.leaveType.Id,leaveAllocationEdit.NumberOfDays))
            {
                ModelState.AddModelError("DaysExceeded", "the allocation exceeds the max days");
         
            }
           if (ModelState.IsValid)
            {
                await _leaveAllocationService.EditAllocation(leaveAllocationEdit);
                return RedirectToAction(nameof(Details), new { UserId = leaveAllocationEdit.Employee.Id });
            }
           var days =leaveAllocationEdit.NumberOfDays;

            leaveAllocationEdit = await _leaveAllocationService.GetAllocationForEmployee(leaveAllocationEdit.Id);
            leaveAllocationEdit.NumberOfDays = days; 
            return View(leaveAllocationEdit);
        }

        public async Task <IActionResult> Details(string? UserId)
        {
            var EmployeeVM = await _leaveAllocationService.GetEmployeeLeaveAllocation(UserId);

            return View(EmployeeVM);
        }
    }
}

LeaveManagementSystem.Web/Controllers/LeaveTypesController.cs
using LeaveManagementSystem.Application.Models.LeaveTypes;
using LeaveManagementSystem.Web.Services.LeaveService;
using Microsoft.EntityFrameworkCore;

namespace LeaveManagementSystem.Web.Controllers
{
    [Authorize(Roles = "administrator")]
    public class LeaveTypesController : Controller
    {
        private readonly ILeaveTypeService _leaveTypeService;

        public LeaveTypesController(ILeaveTypeService leaveTypeService)
        {
            _leaveTypeService = leaveTypeService;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _leaveTypeService.GetAllLeaveTypesAsync();
            return View(data);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var leaveType = await _leaveTypeService.GetleaveTypeAsync<LeaveTypesReadOnly>(id.Value);
            if (leaveType == null)
            {
                return NotFound();
            }
            return View(leaveType);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeaveTypesCreateVM leaveTypesCreateVM)
        {
            if (leaveTypesCreateVM.Name.Contains("vacation"))
            {
                ModelState.AddModelError(nameof(leaveTypesCreateVM.Name), "you're kidding me Right ???");
            }

            bool leaveTypeExists = await _leaveTypeService.CheckLeaveType(leaveTypesCreateVM.Name);

            if (leaveTypeExists)
            {
                ModelState.AddModelError(nameof(leaveTypesCreateVM.Name), "This Leave Type already Exists");

            }
            if (ModelState.IsValid)
            {
                await _leaveTypeService.CreateAsync(leaveTypesCreateVM);
                return RedirectToAction(nameof(Index));
            }

            return View(leaveTypesCreateVM);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveType = await _leaveTypeService.GetleaveTypeAsync<LeaveTypeEditVM>(id.Value);
            if (leaveType == null)
            {
                return NotFound();
            }

            return View(leaveType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, LeaveTypeEditVM leaveTypeEdit)
        {

            bool leaveTypeExists = await _leaveTypeService.CheckLeaveType(leaveTypeEdit.Name);

            if (leaveTypeExists && (id != leaveTypeEdit.Id))
            {
                ModelState.AddModelError(nameof(leaveTypeEdit.Name), "This Leave Type already Exists");
            }

            if (id != leaveTypeEdit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _leaveTypeService.Edit(leaveTypeEdit);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_leaveTypeService.LeaveTypeExists(leaveTypeEdit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(leaveTypeEdit);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leaveType = await _leaveTypeService.GetleaveTypeAsync<LeaveTypesReadOnly>(id.Value);
            if (leaveType == null)
            {
                return NotFound();
            }

            return View(leaveType);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            await _leaveTypeService.Remove(id);


            return RedirectToAction(nameof(Index));
        }


    }
}

LeaveManagementSystem.Web/Controllers/PeriodsController.cs
using AutoMapper;
using LeaveManagementSystem.Application.Models.Period;
using LeaveManagementSystem.Application.Services.PeriodService;
using Microsoft.EntityFrameworkCore;

namespace LeaveManagementSystem.Web.Controllers
{
    [Authorize(Roles = "administrator")]
    public class PeriodsController : Controller
    {

        private readonly IPeriodService _periodService;
        private readonly IMapper _mapper;

        public PeriodsController(IPeriodService periodService, IMapper mapper)
        {
            _periodService = periodService;
            _mapper = mapper;
        }



        // GET: Periods
        public async Task<IActionResult> Index()
        {
            var data = await _periodService.GetAllPeriodsAsync();

            if (data == null || !data.Any())
            {
                return View(data);
            }

            return View(data);
        }

        // GET: Periods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var period = await _periodService.GetPeriodAysnc<PeriodReadOnly>(id.Value);
            if (period == null)
            {
                return NotFound();
            }

            return View(period);
        }

        // GET: Periods/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PeriodCreateVM period)
        {

            var existingPeriod = await _periodService.CheckPeriod(period.Name);

            if (existingPeriod)
            {
                ModelState.AddModelError(nameof(period.Name), "This period already exists.");
            }

            if (ModelState.IsValid)
            {
                await _periodService.AddAsync(period);

                return RedirectToAction(nameof(Index));
            }
            return View(period);
        }

        // GET: Periods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var period = await _periodService.GetPeriodAysnc<PeriodEditVM>(id.Value);
            if (period == null)
            {
                return NotFound();
            }
            return View(period);
        }

        // POST: Periods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PeriodEditVM period)
        {
            if (id != period.Id)
            {
                return NotFound();
            }
            bool leaveTypeExists = await _periodService.CheckPeriod(period.Name);

            if (leaveTypeExists && (id != period.Id))
            {
                ModelState.AddModelError(nameof(period.Name), "This Leave Type already Exists");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _periodService.updatePeriodAysnc(period);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_periodService.PeriodExists(period.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(period);
        }

        // GET: Periods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var period = await _periodService.GetPeriodAysnc<PeriodReadOnly>(id.Value);
            if (period == null)
            {
                return NotFound();
            }

            return View(period);
        }

        // POST: Periods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _periodService.RemoveAsync(id);

            return RedirectToAction(nameof(Index));
        }


    }
}

LeaveManagementSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leave Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeaveManagementSystem.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Leave Management System </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole("administrator"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown"  aria-expanded="false">
                                    Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="" asp-controller="LeaveTypes" asp-action="Index">LeaveTypes</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Periods" asp-action="Index">Periods</a>
                                     <a class="dropdown-item" asp-area="" asp-controller="LeaveAllocation" asp-action="Index">View Employees</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="LeaveRequest" asp-action="ListRequests">View Employee Requests</a>
                                </div>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="LeaveAllocation" asp-action="Details">Veiw Allocations</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-black">
        <div class="container text-white ">
            &copy; 2025 - LeaveManagementSystem.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>